# Site settings
title: Juanma G칩mez
email: jmgomez@iaa.es
author: Juan Manuel G칩mez L칩pez
description: Mi portafolio y algunas cosillas m치s...
url: 

#plugins 
plugins: [jekyll-paginate]
paginate: 3

# Social icons
show_social_icons: true
github_username: jmgomez-IAA
twitter_username: grLean

# Build settings
permalink: :title/
sass:
  sass_dir: css

